[workspace]
authors = ["Michele Ceriotti <michele.ceriotti@epfl.ch>"]
channels = ["conda-forge"]
name = "sketchmap"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]
build = { cmd = "make" }

[dependencies]
compilers = ">=1.11.0,<2"
openblas = ">=0.3.30,<0.4"
make = ">=4.4.1,<5"
